# Generated by Django 2.1.1 on 2018-09-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_1', models.CharField(default='none', max_length=50, null='none')),
                ('pro_2', models.CharField(default='none', max_length=50, null='none')),
                ('pro_3', models.CharField(default='none', max_length=50, null='none')),
            ],
        ),
    ]
