# Generated by Django 2.1.1 on 2018-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jungjong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_real',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='none', max_length=50, null='none')),
                ('pro_count', models.CharField(default='none', max_length=50, null='none')),
            ],
        ),
    ]
